# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b9c9db4986dafc8509c14ab595072f520db204c83e63fc682c4b6e327b41e2b06cfae765fb3e4717a9397fe305a945327965d786ecff2da62c8d772cc7dd9c3

test:
  secret_key_base: 2cefd8a1318c1810afafc36fd4abdd82b6b50450b27deaacdafa7f625a46f6482251dbc3056c2c367814dc3294ba3e6f319814962639626dbf4f2ac7a7b3f05d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
